# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='api.Coin')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_markets', to='api.Coin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('volumn', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('sequence', models.PositiveIntegerField(blank=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.Market')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
