# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('params', models.TextField(default=b'')),
                ('result', models.CharField(max_length=128)),
                ('expected', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
