# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-15 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190615_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='querytest',
            name='passed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
